### ISSUE TITLE
Error Query.run hacer post del signup

### ISSUE THREAD

**Issue by arturoprietovic** [IIC2513/Syllabus#123]
Estoy siguiendo la capsula 8.2 y al seguir al pie de la letra el primer post me salta el siguiente error:

<img width="969" alt="image" src="https://github.com/IIC2513/Syllabus/assets/65640660/b88face2-9f59-4a53-9d4e-f32332eecf04">

Lo copio acá también:
```
<-- POST /signup
Executing (default): SELECT "id", "username", "passwod", "mail", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."mail" = 'loco@gmail.com' LIMIT 1;
  xxx POST /signup 500 14ms -

  Error
      at Query.run (/home/artur/WEB/grupo-Charlie-Kelly-backend/backend/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
      at /home/artur/WEB/grupo-Charlie-Kelly-backend/backend/node_modules/sequelize/lib/sequelize.js:315:28
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryInterface.select (/home/artur/WEB/grupo-Charlie-Kelly-backend/backend/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
      at async User.findAll (/home/artur/WEB/grupo-Charlie-Kelly-backend/backend/node_modules/sequelize/lib/model.js:1140:21)
      at async User.findOne (/home/artur/WEB/grupo-Charlie-Kelly-backend/backend/node_modules/sequelize/lib/model.js:1240:12)
      at async /home/artur/WEB/grupo-Charlie-Kelly-backend/backend/src/routes/authentication.js:8:16
      at async logger (/home/artur/WEB/grupo-Charlie-Kelly-backend/backend/node_modules/koa-logger/index.js:67:7)
```

Alguna ayuda para resolver esto? Gracias!

**Comment by valeeeriquelme** [comment]
Que tienes en la línea que indica el error? authentication.js 8:16

**Comment by arturoprietovic** [comment]
Ya lo resolvi graciass
